### ISSUE TITLE
V 1.0?

### ISSUE THREAD

**Issue by cmountvpr** [djpeterso23662/CrystalPalace#2]
I sure hope you plan to update the Crystal Palace to v 1.0. It's a favorite module of mine!

**Comment by djpeterso23662** [comment]
Hi @cmountvpr!  Thanks for posting.  Crystal Palace for VCV Rack v1.0 is nearly ready.  I have posted the Linux and Windows versions under Releases here on GitHub, and plan to post the Mac version tomorrow.  Andrew will add it to the VCV Rack Plugin Manager shortly after that.

**Comment by danhphotos** [comment]
Thank you very much for updating Perspex to 1.0, it is my favorite Rack module!

**Comment by djpeterso23662** [comment]
You are very welcome! I am so glad to hear that you like it! The Mac version is now posted as well.

**Comment by danhphotos** [comment]
I don't have a Mac I am using a PC, but thanks for updating everyone. 

So much fun in such a simple concept! I have had hours of fun in the last few days! Thanks again!

    On Friday, January 24, 2020, 6:06:20 AM PST, David Peterson <notifications@github.com> wrote:  
 
 
You are very welcome! I am so glad to hear that you like it! The Mac version is now posted as well.
